FROM ubuntu:24.04 as build

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -y \
		build-essential \
		gnome-session \
		libx11-dev \
		libxinerama-dev \
		libxkbcommon-dev \
		libxtst-dev \
		openbox \
		ruby \
		x11-utils \
		xterm \
		xvfb \
	&& rm -rf /var/lib/apt/lists/*

COPY . /build
RUN make -C /build update-version
RUN make -C /build all

CMD make -C /build test

